<?php
/**
 * AccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MicroCoin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MicroCoin API
 *
 * MicroCoin rider is an API server for the MicroCoin ecosystem.  It acts as the interface between MicroCoin network and applications that want to access the MicroCoin network.  It allows you to submit transactions to the network, check the status of accounts, subscribe to transactions, etc.  Rider provides a RESTful API to allow client applications to interact with the MicroCoin network.  You can communicate with Rider using cURL or just your web browser. However, if you’re building a client application, you’ll likely want to use a MicroCoin SDK in the language of your client
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MicroCoin;

use \MicroCoin\Configuration;
use \MicroCoin\ApiException;
use \MicroCoin\ObjectSerializer;

/**
 * AccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  MicroCoin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for commitChangeKey
     *
     * Commit change key transaction.
     *
     */
    public function testCommitChangeKey()
    {
    }

    /**
     * Test case for commitPurchaseAccount
     *
     * Commit signed Purchase account transaction.
     *
     */
    public function testCommitPurchaseAccount()
    {
    }

    /**
     * Test case for getAccount
     *
     * Account detils.
     *
     */
    public function testGetAccount()
    {
    }

    /**
     * Test case for getOffers
     *
     * Get list of accounts for sale.
     *
     */
    public function testGetOffers()
    {
    }

    /**
     * Test case for getTransactions
     *
     * Retrieve account transaction history.
     *
     */
    public function testGetTransactions()
    {
    }

    /**
     * Test case for myAccounts
     *
     * Get a list of accounts belonging to the key.
     *
     */
    public function testMyAccounts()
    {
    }

    /**
     * Test case for startChangeKey
     *
     * Create new change key transaction.
     *
     */
    public function testStartChangeKey()
    {
    }

    /**
     * Test case for startPurchaseAccount
     *
     * Create purchase account transaction.
     *
     */
    public function testStartPurchaseAccount()
    {
    }
}
